<a href="https://colab.research.google.com/github/AmeeraAhmed27/AmeeraAhmed27/blob/main/session4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# --- TASK A: BASIC ---
print("--- TASK A: BASIC ---")

# 1. Create a NumPy array from a Python list of 10 numbers
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 2. Print array attributes
print(f"Original array: {arr_1d}")
print(f"Dtype: {arr_1d.dtype}")
print(f"Shape: {arr_1d.shape}")

# 3. Simple arithmetic (Scalar operations)
print(f"Array + 5: {arr_1d + 5}")
print(f"Array * 2: {arr_1d * 2}")
print("\n")

--- TASK A: BASIC ---
Original array: [ 1  2  3  4  5  6  7  8  9 10]
Dtype: int64
Shape: (10,)
Array + 5: [ 6  7  8  9 10 11 12 13 14 15]
Array * 2: [ 2  4  6  8 10 12 14 16 18 20]




In [3]:
# --- TASK B: INTERMEDIATE ---
print("--- TASK B: INTERMEDIATE ---")

# 1. Create a 3x3 array with numbers 1 to 9
arr_2d = np.arange(1, 10).reshape(3, 3)
print("2D array:")
print(arr_2d)

# 2. Statistical operations
# axis=1 performs the operation across columns (summing each row)
# axis=0 performs the operation across rows (summing each column)
print(f"Sum along rows: {arr_2d.sum(axis=1)}")
print(f"Sum along columns: {arr_2d.sum(axis=0)}")
print(f"Mean: {arr_2d.mean()}, Min: {arr_2d.min()}, Max: {arr_2d.max()}, Std: {arr_2d.std():.5f}")

# 3. Slicing
# [1, :] selects the index 1 row (2nd row)
# [:, -1] selects the last index of the columns
print(f"Second row: {arr_2d[1, :]}")
print(f"Last column: {arr_2d[:, -1]}")

# 4. Reshaping
print(f"Reshaped 1x9: {arr_2d.reshape(1, 9)}")
print(f"Reshaped 9x1:\n{arr_2d.reshape(9, 1)}")
print("\n")

--- TASK B: INTERMEDIATE ---
2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum along rows: [ 6 15 24]
Sum along columns: [12 15 18]
Mean: 5.0, Min: 1, Max: 9, Std: 2.58199
Second row: [4 5 6]
Last column: [3 6 9]
Reshaped 1x9: [[1 2 3 4 5 6 7 8 9]]
Reshaped 9x1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]




In [4]:
# --- TASK C: ADVANCED ---
print("--- TASK C: ADVANCED ---")

# 1. Create two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# 2. Vectorized operations (Element-wise)
print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"(a + b) / 2: {(a + b) / 2}")

# 3. Broadcasting
# Adding a (1, 5) shape array to a (2, 5) shape array
ones_array = np.ones((2, 5))
broadcasted_sum = a + ones_array
print("Broadcasting (a + 2x5 ones):")
print(broadcasted_sum)



# 4. Random 5x5 array
rand_arr = np.random.rand(5, 5)
print(f"\nRandom 5x5 Array Sum: {rand_arr.sum()}")
print(f"Mean of each row: {rand_arr.mean(axis=1)}")
print(f"Max of each column: {rand_arr.max(axis=0)}")

--- TASK C: ADVANCED ---
a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
(a + b) / 2: [ 5.5 11.  16.5 22.  27.5]
Broadcasting (a + 2x5 ones):
[[2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6.]]

Random 5x5 Array Sum: 11.899526120078946
Mean of each row: [0.63189324 0.72288663 0.29375833 0.36431651 0.36705051]
Max of each column: [0.8766462  0.89433021 0.88274361 0.94523949 0.94111239]
